export default {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: false,
  trailingComma: "all",
  ignorePatterns: [
    ".agents/**",
    ".git/**",
    ".superpowers/**",
    ".worktrees/**",
    "build/**",
    "dist/**",
    "docs/**",
    "images/**",
    "node_modules/**",
    "out/**",
    "resources/**",
    "*.md",
    "*.yml",
    "*.yaml",
  ],
};
