/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Block: typeof import('./src/components/md-editor/Block.vue')['default']
    Blockquote: typeof import('./src/components/md-editor/Blockquote.vue')['default']
    BottomBar: typeof import('./src/components/bottom-bar/index.vue')['default']
    CodeBlock: typeof import('./src/components/md-editor/CodeBlock.vue')['default']
    copy: (typeof import('./src/components/menu-bar/menu-bar copy/index.vue'))['default']
    DirTree: typeof import('./src/components/dir-tree/index.vue')['default']
    ImageTooltip: typeof import('./src/components/md-editor/ImageTooltip.vue')['default']
    ListItem: typeof import('./src/components/md-editor/ListItem.vue')['default']
    MdEditor: typeof import('./src/components/md-editor/index.vue')['default']
    MenuBar: typeof import('./src/components/menu-bar/index.vue')['default']
    Slash: typeof import('./src/components/md-editor/Slash.vue')['default']
    SyncSettings: typeof import('./src/components/sync-settings/index.vue')['default']
    TableSelector: typeof import('./src/components/md-editor/table-widget/table-selector.vue')['default']
    TableTooltip: typeof import('./src/components/md-editor/table-widget/table-tooltip.vue')['default']
    Toolbar: typeof import('./src/components/md-editor/Toolbar.vue')['default']
    Tooltip: typeof import('./src/components/md-editor/Tooltip.vue')['default']
    TooltipIcon: typeof import('./src/components/md-editor/table-widget/tooltip-icon.vue')['default']
  }
}
