/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: (typeof import("ant-design-vue/es"))["Form"]
    AFormItem: (typeof import("ant-design-vue/es"))["FormItem"]
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioGroup: (typeof import("ant-design-vue/es"))["RadioGroup"]
    ASpace: (typeof import("ant-design-vue/es"))["Space"]
    ASpin: (typeof import("ant-design-vue/es"))["Spin"]
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BottomBar: typeof import('./src/components/bottom-bar/index.vue')['default']
    ContextMenu: typeof import('./src/components/dir-tree/components/contextMenu.vue')['default']
    DirSettings: typeof import('./src/components/settings-modal/components/dir-settings/index.vue')['default']
    DirTree: typeof import('./src/components/dir-tree/index.vue')['default']
    MdEditor: typeof import('./src/components/md-editor/index.vue')['default']
    MenuBar: typeof import('./src/components/menu-bar/index.vue')['default']
    Modal: typeof import('./src/components/dir-tree/components/modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/settings-modal/index.vue')['default']
    Spinner: typeof import('./src/components/spinner/index.vue')['default']
    SyncSettings: typeof import('./src/components/settings-modal/components/sync-settings/index.vue')['default']
    ToolsAction: typeof import('./src/components/tools-action/index.vue')['default']
    Upload: typeof import('./src/components/dir-tree/components/upload.vue')['default']
  }
}
