/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A: (typeof import("./src/components/menu-bar/components/a.vue"))["default"]
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: (typeof import("ant-design-vue/es"))["MenuDivider"]
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATree: (typeof import("ant-design-vue/es"))["Tree"]
    BarAction: (typeof import("./src/components/menu-bar/components/bar-action.vue"))["default"]
    Block: typeof import('./src/components/md-editor/Block.vue')['default']
    Blockquote: typeof import('./src/components/md-editor/Blockquote.vue')['default']
    BottomBar: typeof import('./src/components/bottom-bar/index.vue')['default']
    CodeBlock: typeof import('./src/components/md-editor/CodeBlock.vue')['default']
    copy: (typeof import("./src/components/menu-bar/menu-bar copy/index.vue"))["default"]
    DirTree: typeof import('./src/components/dir-tree/index.vue')['default']
    ImageTooltip: typeof import('./src/components/md-editor/ImageTooltip.vue')['default']
    ListItem: typeof import('./src/components/md-editor/ListItem.vue')['default']
    MdAction: (typeof import("./src/components/menu-bar/components/md-action.vue"))["default"]
    MdEditor: typeof import('./src/components/md-editor/index.vue')['default']
    MenuBar: typeof import('./src/components/menu-bar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slash: typeof import('./src/components/md-editor/Slash.vue')['default']
    Spinner: typeof import('./src/components/spinner/index.vue')['default']
    SyncSettings: typeof import('./src/components/sync-settings/index.vue')['default']
    TableSelector: typeof import('./src/components/md-editor/table-widget/table-selector.vue')['default']
    TableTooltip: typeof import('./src/components/md-editor/table-widget/table-tooltip.vue')['default']
    Toolbar: typeof import('./src/components/md-editor/Toolbar.vue')['default']
    ToolsAction: typeof import('./src/components/tools-action/index.vue')['default']
    Tooltip: typeof import('./src/components/md-editor/Tooltip.vue')['default']
    TooltipIcon: typeof import('./src/components/md-editor/table-widget/tooltip-icon.vue')['default']
    Upload: typeof import('./src/components/dir-tree/components/upload.vue')['default']
  }
}
